#!/usr/bin/expect

set timeout 10

spawn php /var/www/seat/artisan seat:admin:reset
expect "> " { send "password\r" }
expect eof

spawn php /var/www/seat/artisan seat:admin:email
expect "> " { send "admin@docker.local\r" }
expect eof