version: "3.2"

services:

  mariadb:
    image: mariadb:10.3
    container_name: seat-mariadb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "${MYSQL_RANDOM_ROOT_PASSWORD}"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - "mariadb-data:/var/lib/mysql"
    networks:
      - seat-network
    ports:
      - "${MYSQL_EXTERNAL_PORT}:3306"

  redis:
    image: redis:5-alpine
    container_name: seat-redis
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - "redis-data:/data"
    networks:
      - seat-network

  nginx:
    image: nginx:1.16-alpine
    depends_on:
      - seat-app
    container_name: seat-nginx
    restart: always
    environment:
      - NGINX_HOST=${NGINX_HOST}
    volumes:
      - ${SEAT_CODE}/public:/var/www/seat/public
      - ./config/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ${NGINX_CERTIFICATE_PATH}:/etc/ssl/fullchain.pem
      - ${NGINX_PRIVATE_KEY_PATH}:/etc/ssl/privkey.pem
      # Remove the comment below to enable nginx logs to disk.
      #- ./logs/nginx/:/var/log/nginx/
    ports:
      - "${NGINX_HTTP}:80"
      - "${NGINX_HTTPS}:443"
    command: /bin/sh -c "envsubst '${NGINX_HOST}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    networks:
      - seat-network

  seat-app:
    build:
      context: ./eveseat-app
    image: seat-app
    container_name: seat-app
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file:
      - ./.env
    volumes:
      - ${SEAT_CODE}:/var/www/seat
    depends_on:
      - mariadb
      - redis
    networks:
      - seat-network

  seat-worker:
    build:
      context: ./eveseat-worker
    image: eveseat-worker
    container_name: seat-worker
    restart: always
    env_file:
      - ./.env
    volumes:
      - ${SEAT_CODE}:/var/www/seat
    depends_on:
      - seat-app # so that we can get composer installed
      - mariadb
      - redis
    networks:
      - seat-network

  seat-cron:
    build:
      context: ./eveseat-cron
    image: seat-cron
    container_name: seat-cron
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file:
      - ./.env
    volumes:
      - ${SEAT_CODE}:/var/www/seat
    depends_on:
      - mariadb
      - redis
    networks:
      - seat-network

volumes:
    redis-data:
    mariadb-data:

networks:
    seat-network:
