version: "3.2"

services:

  mariadb:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "${MYSQL_RANDOM_ROOT_PASSWORD}"
    volumes:
      - "mariadb-data:/var/lib/mysql"
    networks:
      - seat-dev-network
    ports:
      - "${MYSQL_EXTERNAL_PORT}:3306"

  redis:
    image: redis:5-alpine
    restart: always
    networks:
      - seat-dev-network

  traefik:
    image: traefik:2.2
    restart: always
    command:
      - --log.level=INFO
      - --api=true
      - --api.dashboard=true
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --entryPoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
    ports:
      - ${TRAEFIK_HTTPS}:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.${WEB_DOMAIN}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
    networks:
      - seat-dev-network

  seat-web:
    build:
      context: ./seat
    image: seat
    restart: always
    command: web
    env_file:
      - .env
    volumes:
      - ${SEAT_CODE}:/var/www/seat
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seat-web.rule=Host(`web.${WEB_DOMAIN}`)"
      - "traefik.http.routers.seat-web.entrypoints=websecure"
    depends_on:
      - mariadb
      - redis
    networks:
      - seat-dev-network

  seat-worker:
    build:
      context: ./seat
    image: seat
    restart: always
    command: worker
    env_file:
      - .env
    volumes:
      - ${SEAT_CODE}:/var/www/seat
    depends_on:
      - seat-web # so that we can get composer installed
      - mariadb
      - redis
    networks:
      - seat-dev-network

  seat-cron:
    build:
      context: ./seat
    image: seat
    restart: always
    command: cron
    env_file:
      - .env
    volumes:
      - ${SEAT_CODE}:/var/www/seat
    depends_on:
      - seat-web # so that we can get composer installed
      - mariadb
      - redis
    networks:
      - seat-dev-network

volumes:
    redis-data:
    mariadb-data:

networks:
    seat-dev-network:
