version: "3.2"

services:

  mariadb:
    image: mariadb:10.3
    container_name: eveseat-mariadb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: seat
      MYSQL_PASSWORD: seat
      MYSQL_DATABASE: seat
    volumes:
      - "mariadb-data:/var/lib/mysql"
    networks:
      - seat-network
    ports:
      - "3366:3306"

  redis:
    image: redis:3
    container_name: eveseat-redis
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - "redis-data:/data"
    networks:
      - seat-network

  nginx:
    image: nginx:1.13-alpine
    depends_on:
      - seat-app
    container_name: eveseat-nginx
    restart: always
    volumes:
      - type: bind
        source: ${SEAT_CORE}/public
        target: /var/www/seat/public
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      # Remove the comment below to enable nginx logs to disk.
      #- ./logs/nginx/:/var/log/nginx/
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - seat-network

  seat-app:
    build:
      context: ./eveseat-app
    container_name: eveseat-app
    restart: always
    volumes:
      - type: bind
        source: ${SEAT_CORE}
        target: /var/www/seat
      - type: bind
        source: ${SEAT_API}
        target: /var/www/seat/packages/eveseat/api
      - type: bind
        source: ${SEAT_CONSOLE}
        target: /var/www/seat/packages/eveseat/console
      - type: bind
        source: ${SEAT_EVEAPI}
        target: /var/www/seat/packages/eveseat/eveapi
      - type: bind
        source: ${SEAT_SERVICES}
        target: /var/www/seat/packages/eveseat/services
      - type: bind
        source: ${SEAT_WEB}
        target: /var/www/seat/packages/eveseat/web
      - type: bind
        source: ${SEAT_NOTIFICATIONS}
        target: /var/www/seat/packages/eveseat/notifications
      - type: bind
        source: ${SEAT_ESEYE}
        target: /var/www/seat/packages/eveseat/eseye
    depends_on:
      - mariadb
      - redis
    networks:
      - seat-network

  seat-worker:
    build:
      context: ./eveseat-worker
    container_name: eveseat-worker
    restart: always
    volumes:
      - type: bind
        source: ${SEAT_CORE}
        target: /var/www/seat
      - type: bind
        source: ${SEAT_API}
        target: /var/www/seat/packages/eveseat/api
      - type: bind
        source: ${SEAT_CONSOLE}
        target: /var/www/seat/packages/eveseat/console
      - type: bind
        source: ${SEAT_EVEAPI}
        target: /var/www/seat/packages/eveseat/eveapi
      - type: bind
        source: ${SEAT_SERVICES}
        target: /var/www/seat/packages/eveseat/services
      - type: bind
        source: ${SEAT_WEB}
        target: /var/www/seat/packages/eveseat/web
      - type: bind
        source: ${SEAT_NOTIFICATIONS}
        target: /var/www/seat/packages/eveseat/notifications
      - type: bind
        source: ${SEAT_ESEYE}
        target: /var/www/seat/packages/eveseat/eseye
    depends_on:
      - seat-app # so that we can get composer installed
      - mariadb
      - redis
    networks:
      - seat-network

volumes:
    redis-data:
    mariadb-data:

networks:
    seat-network:
